In [17]:
import pandas as pd

raw_data = pd.read_csv('ENFR 2018 - Base usuario.txt', sep = '|')

raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 29224 entries, 0 to 29223
Columns: 287 entries, id to wf3p
dtypes: float64(186), int64(101)
memory usage: 64.0 MB

# Bloque Individual

## Datos sociodemográficos del individuo seleccionado (CH / BI)

In [9]:
columnas = [
    "bhch02",
    "bhch03",
    "bhch04",
    "bhch05",
    "rango_edad",
    "nivel_instruccion",
    "nivel_instruccion_agrupado",
    "bhch10_01",
    "bhch10_02",
    "bhch10_03",
    "bhch10_04",
    "bhch10_05",
    "bhch10_06",
    "bhch10_99",
    "cobertura_salud"
]

raw_data_sociodemografico = raw_data[columnas]
raw_data_sociodemografico.head(5)
raw_data_sociodemografico.info()

<class 'pandas.DataFrame'>
RangeIndex: 29224 entries, 0 to 29223
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   bhch02                      29224 non-null  int64
 1   bhch03                      29224 non-null  int64
 2   bhch04                      29224 non-null  int64
 3   bhch05                      29224 non-null  int64
 4   rango_edad                  29224 non-null  int64
 5   nivel_instruccion           29224 non-null  int64
 6   nivel_instruccion_agrupado  29224 non-null  int64
 7   bhch10_01                   17395 non-null  float64
 8   bhch10_02                   2222 non-null   float64
 9   bhch10_03                   1077 non-null   float64
 10  bhch10_04                   697 non-null    float64
 11  bhch10_05                   585 non-null    float64
 12  bhch10_06                   8248 non-null   float64
 13  bhch10_99                   154 non-null    float64
 14  cobertura_salud             29224 non-null  int64
dtypes: float64(7), int64(8)
memory usage: 3.3 MB

## Situación laboral

In [11]:
columnas = ["bisl01",
            "bisl02",
            "bisl03",
            "bisl04",
            "bisl05",
            "bisl06",
            "condicion_actividad"]
raw_data_situ_laboral = raw_data[columnas]
raw_data_situ_laboral.head(5)
raw_data_situ_laboral.info()

<class 'pandas.DataFrame'>
RangeIndex: 29224 entries, 0 to 29223
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   bisl01               29224 non-null  int64
 1   bisl02               11767 non-null  float64
 2   bisl03               232 non-null    float64
 3   bisl04               1721 non-null   float64
 4   bisl05               396 non-null    float64
 5   bisl06               17668 non-null  float64
 6   condicion_actividad  29224 non-null  int64
dtypes: float64(5), int64(2)
memory usage: 1.6 MB

## Salud general

In [13]:
columnas = ["bisg01",
            "bisg02",
            "bisg03",
            "bisg04",
            "bisg05",
            "bisg06",]
raw_data_salud_general = raw_data[columnas]
raw_data_salud_general.head(5)
raw_data_salud_general.info()

<class 'pandas.DataFrame'>
RangeIndex: 29224 entries, 0 to 29223
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   bisg01  29224 non-null  int64
 1   bisg02  29224 non-null  int64
 2   bisg03  29224 non-null  int64
 3   bisg04  29224 non-null  int64
 4   bisg05  29224 non-null  int64
 5   bisg06  29224 non-null  int64
dtypes: int64(6)
memory usage: 1.3 MB

## Actividad física

In [18]:
colunas = ["biaf01",
           "biaf02_m",
           "biaf02_99",
           "biaf03",
           "biaf04_m",
           "biaf04_99",
           "biaf05",
           "biaf06_m",
           "biaf06_99",
           "biaf07_m",
           "biaf07_99",
           "biaf08",
           "biaf09",
           "biaf10_01",
           "biaf10_02",
           "biaf10_03",
           "biaf10_04",
           "nivel_actividad_fisica",
           "barreras_actividad_fisica"
           ]
raw_data_actividad_fisica = raw_data[colunas]
raw_data_actividad_fisica.head(5)

,biaf01,biaf02_m,biaf02_99,biaf03,biaf04_m,biaf04_99,biaf05,biaf06_m,biaf06_99,biaf07_m,biaf07_99,biaf08,biaf09,biaf10_01,biaf10_02,biaf10_03,biaf10_04,nivel_actividad_fisica,barreras_actividad_fisica
0,4,500.0,NaN,4,120.0,NaN,7,300.0,NaN,480.0,NaN,NaN,2.0,2.0,2.0,1.0,1.0,1.0,1
1,3,210.0,NaN,1,30.0,NaN,7,180.0,NaN,600.0,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0,1
2,0,NaN,NaN,3,180.0,NaN,7,270.0,NaN,540.0,NaN,NaN,10.0,1.0,1.0,1.0,1.0,2.0,9
3,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,120.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,3.0,1
4,0,NaN,NaN,2,180.0,NaN,7,120.0,NaN,480.0,NaN,NaN,2.0,1.0,1.0,1.0,2.0,2.0,1

## Tabaco

In [20]:
columnas = [
    "bita01",
    "bita02",
    "bita02_99",
    "bita03",
    "bita04",
    "bita04_01",
    "bita04_02",
    "bita05",
    "bita06_a",
    "bita06_b",
    "bita06_b_99",
    "bita06_c",
    "bita06_d",
    "bita07",
    "bita07_99",
    "bita08",
    "bita09_01",
    "bita09_02",
    "bita09_03",
    "bita09_04",
    "bita09_05",
    "bita09_06",
    "bita10_01",
    "bita10_02",
    "bita10_03",
    "bita10_04",
    "bita10_05",
    "bita10_06",
    "bita11",
    "bita12",
    "bita13",
    "bita14",
    "bita15",
    "bita16",
    "consumo_tabaco_100",
    "ta_paquete_y_armado",
    "ta_dejar_fumar",
    "ta_otros_productos",
    "hta_nofumadores",
    "ta_perc_publicidad",
    "ta_percepcion_riesgo",
    "imagenes_tabaco"
]
raw_data_tabaco = raw_data[columnas]
raw_data_tabaco.head(5)

,bita01,bita02,bita02_99,bita03,bita04,bita04_01,bita04_02,bita05,bita06_a,bita06_b,...,bita15,bita16,consumo_tabaco_100,ta_paquete_y_armado,ta_dejar_fumar,ta_otros_productos,hta_nofumadores,ta_perc_publicidad,ta_percepcion_riesgo,imagenes_tabaco
0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2,3,NaN,NaN,2,2.0,1.0,1.0,NaN
1,1,20.0,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,1,3,NaN,NaN,2,1.0,1.0,2.0,NaN
2,1,18.0,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2,2,NaN,NaN,2,1.0,1.0,1.0,NaN
3,1,14.0,NaN,1.0,1.0,2.0,1.0,1.0,1.0,20.0,...,2.0,1,1,2.0,2.0,2,NaN,2.0,1.0,2.0
4,1,13.0,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,99,3,NaN,NaN,2,1.0,1.0,1.0,NaN

## Hipertensión arterial

In [ ]:
columnas = [
    "biha01",
    "biha02",
    "biha03",
    "biha04",
    "biha05_01",
    "biha05_02",
    "biha06",
    "biha06_99",
    "biha07",
    "biha08",
    "biha09",
    "biha10",
    "biha11",
    "biha11_99",
    "biha12",
    "biha13",
    "biha14",
    "biha15",
    "control_hipertension",
    "prevalencia_hipertension",
]
raw_data_hipertension = raw_data[columnas]
raw_data_hipertension.head(5)

## Peso corporal

In [22]:
columnas = [
    "bipc01",
    "bipc02",
    "bipc03",
    "bipc04",
    "bipc04_99",
    "bipc05",
    "bipc05_99",
    "imc",
    "imc_categorias",
]
raw_data_peso_corporal = raw_data[columnas]
raw_data_peso_corporal.info()

<class 'pandas.DataFrame'>
RangeIndex: 29224 entries, 0 to 29223
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bipc01          29224 non-null  int64
 1   bipc02          9240 non-null   float64
 2   bipc03          23823 non-null  float64
 3   bipc04          28213 non-null  float64
 4   bipc04_99       1011 non-null   float64
 5   bipc05          27548 non-null  float64
 6   bipc05_99       1676 non-null   float64
 7   imc             26995 non-null  float64
 8   imc_categorias  29224 non-null  int64
dtypes: float64(7), int64(2)
memory usage: 2.0 MB

## Alimentación

In [23]:
columnas= [
    "bial01",
    "bial02",
    "bial03",
    "bial03_99",
    "bial04",
    "bial04_99",
    "bial05",
    "bial05_99",
    "bial06",
    "bial06_99",
    "bial07",
    "bial08",
    "bial09",
    "bial10",
    "promedio_fv_diario",
    "consumo_fv",
    "barreras_fyv",
    "tipo_dieta_razones",
]
raw_data_alimentacion = raw_data[columnas]
raw_data_alimentacion.head(5)

,bial01,bial02,bial03,bial03_99,bial04,bial04_99,bial05,bial05_99,bial06,bial06_99,bial07,bial08,bial09,bial10,promedio_fv_diario,consumo_fv,barreras_fyv,tipo_dieta_razones
0,2,3,7.0,NaN,3.0,NaN,7.0,NaN,1.0,NaN,8,2,NaN,2,4.00,2,1,NaN
1,2,2,7.0,NaN,5.0,NaN,5.0,NaN,2.0,NaN,1,2,NaN,1,6.43,1,4,NaN
2,1,1,5.0,NaN,2.0,NaN,5.0,NaN,2.0,NaN,2,2,NaN,2,2.86,2,1,NaN
3,99,1,3.0,NaN,1.0,NaN,7.0,NaN,1.0,NaN,9,2,NaN,99,1.43,2,1,NaN
4,1,3,7.0,NaN,1.0,NaN,3.0,NaN,1.0,NaN,2,2,NaN,1,1.43,2,1,NaN

## Colesterol

In [25]:
columnas = [
    "bico01",
    "bico02",
    "bico03",
    "bico04",
    "bico05_01",
    "bico05_02",
    "control_colesterol",
]
raw_data_colesterol = raw_data[columnas]
raw_data_colesterol.head(5)

   bico01  bico02  bico03  bico04  bico05_01  bico05_02  control_colesterol
0       1     2.0       2     NaN        NaN        NaN                 NaN
1       1     2.0       1     2.0        NaN        NaN                 1.0
2       1     2.0       2     NaN        NaN        NaN                 NaN
3       1     2.0       1     1.0        2.0        1.0                 1.0
4       1     1.0       2     NaN        NaN        NaN                 NaN

## Consumo de alcohol

In [26]:
columnas = [
    "bica01",
    "bica02",
    "bica03_01",
    "bica03_02",
    "bica03_99",
    "bica04_01_b",
    "bica04_01_c",
    "bica04_02_b",
    "bica04_02_c",
    "bica04_03_b",
    "bica04_03_c",
    "bica04_04",
    "bica05_01_b",
    "bica05_01_c",
    "bica05_02_b",
    "bica05_02_c",
    "bica05_03_b",
    "bica05_03_c",
    "bica05_04",
    "bica06",
    "bica07",
    "consumo_regular_riesgo",
    "consumo_episodico_excesivo",
]
raw_data_alcohol = raw_data[columnas]
raw_data_alcohol.head(5)

,bica01,bica02,bica03_01,bica03_02,bica03_99,bica04_01_b,bica04_01_c,bica04_02_b,bica04_02_c,bica04_03_b,...,bica05_01_c,bica05_02_b,bica05_02_c,bica05_03_b,bica05_03_c,bica05_04,bica06,bica07,consumo_regular_riesgo,consumo_episodico_excesivo
0,1,1.0,1.0,NaN,NaN,1.0,NaN,NaN,98.0,NaN,...,NaN,1.0,NaN,NaN,98.0,2.0,2.0,2,2.0,2.0
1,1,1.0,NaN,1.0,NaN,NaN,98.0,1.0,NaN,NaN,...,98.0,NaN,98.0,NaN,98.0,2.0,2.0,2,2.0,2.0
2,1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0
3,1,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0
4,1,1.0,1.0,NaN,NaN,1.5,NaN,NaN,98.0,NaN,...,98.0,NaN,98.0,NaN,98.0,2.0,2.0,99,2.0,2.0

## Diabetes

In [27]:
columnas = [
    "bidi01",
    "bidi02",
    "bidi03",
    "bidi04_01",
    "bidi04_02",
    "bidi04_03",
    "bidi05",
    "bidi06_01",
    "bidi06_02",
    "bidi07",
    "bidi08",
    "bidi09",
    "bidi10",
    "bidi11",
    "bidi12",
    "bidi13",
    "bidi14",
    "control_diabetes",
    "prevalencia_diabetes",
]
raw_data_diabetes = raw_data[columnas]
raw_data_diabetes.head(5)

,bidi01,bidi02,bidi03,bidi04_01,bidi04_02,bidi04_03,bidi05,bidi06_01,bidi06_02,bidi07,bidi08,bidi09,bidi10,bidi11,bidi12,bidi13,bidi14,control_diabetes,prevalencia_diabetes
0,2,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2
1,2,NaN,NaN,NaN,NaN,NaN,NaN,2,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2
2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2
3,2,NaN,NaN,NaN,NaN,NaN,NaN,2,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2
4,2,NaN,NaN,NaN,NaN,NaN,NaN,2,99,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2

## Lesiones

In [28]:
columnas = ["bile01",
    "bile02",
    "bile03", ]

raw_data_lesiones = raw_data[columnas]
raw_data_lesiones.head(5)

   bile01  bile02  bile03
0       1      98       1
1      98      98       1
2      98       1       1
3      98      98       1
4      98      98       1

## Prácticas preventivas

In [29]:
columnas = [
    "bipp01",
    "bipp02",
    "bipp03",
    "bipp04",
    "control_mamografia",
    "control_pap",
]
raw_data_practicas_preventivas = raw_data[columnas]
raw_data_practicas_preventivas.head(5)

   bipp01  bipp02  bipp03  bipp04  control_mamografia  control_pap
0     NaN     NaN     NaN     NaN                 NaN          NaN
1     1.0     1.0     1.0     1.0                 1.0          1.0
2     2.0     NaN     1.0     1.0                 2.0          1.0
3     1.0     3.0     1.0     2.0                 2.0          1.0
4     NaN     NaN     NaN     NaN                 NaN          NaN

## Prevención del cáncer colorrectal

In [30]:
columnas = [
    "bicc01_01",
    "bicc01_02",
    "bicc01_03",
    "bicc02",
    "bicc03",
    "control_colon",
]
raw_data_cancer_colorrectal = raw_data[columnas]
raw_data_cancer_colorrectal.head(5)

   bicc01_01  bicc01_02  bicc01_03  bicc02  bicc03  control_colon
0        NaN        NaN        NaN     NaN     NaN            NaN
1        2.0        1.0        2.0     2.0     3.0            1.0
2        NaN        NaN        NaN     NaN     NaN            NaN
3        2.0        1.0        2.0     2.0     1.0            1.0
4        NaN        NaN        NaN     NaN     NaN            NaN

## Mediciones antropométricas

In [31]:
columnas = [
    "bima01",
    "bima02",
    "bima03",
    "bima04_01_a",
    "bima04_01_b",
    "bima04_02_a",
    "bima04_02_b",
    "bima04_03_a",
    "bima04_03_b",
    "promedio_sistolica",
    "promedio_diastolica",
    "ta_elevada",
    "prevalencia_hipertension_combinada",
    "bima06",
    "bima07",
    "bima09",
    "bima10",
    "imc_bima",
    "imc_categorias_bima",
    "bima12",
    "bima13",
    "bima14",
]

raw_data_mediciones_antro = raw_data[columnas]
raw_data_mediciones_antro.head(5)

,bima01,bima02,bima03,bima04_01_a,bima04_01_b,bima04_02_a,bima04_02_b,bima04_03_a,bima04_03_b,promedio_sistolica,...,prevalencia_hipertension_combinada,bima06,bima07,bima09,bima10,imc_bima,imc_categorias_bima,bima12,bima13,bima14
0,1.0,2.0,1.0,151.0,99.0,147.0,100.0,148.0,97.0,147.5,...,1.0,1.0,181.0,1.0,106.0,32.36,3.0,1.0,103.0,2.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Mediciones químicas

In [32]:
columnas = [
    "bimq01",
    "bimq05",
    "bimq05_01",
    "glucemia_elevada",
    "prevalencia_glucemia_elevada_combinada",
    "findrisc",
    "bimq06",
    "bimq06_01",
    "colesterol_elevado",
    "prevalencia_colesterol_combinada",
]
raw_data_mediciones_quimi = raw_data[columnas]
raw_data_mediciones_quimi.head(5)

,bimq01,bimq05,bimq05_01,glucemia_elevada,prevalencia_glucemia_elevada_combinada,findrisc,bimq06,bimq06_01,colesterol_elevado,prevalencia_colesterol_combinada
0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Factores de ponderacion muestral

In [33]:
columnas = ["wf1p",
            "wf2p",
            "wf3p"]
raw_data_factores_ponderacion = raw_data[columnas]
raw_data_factores_ponderacion.head(5)

   wf1p  wf2p  wf3p
0  2378  4464     0
1  3588     0     0
2  2740     0     0
3   493     0     0
4  2016     0     0